<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_iklan</name>
   <tag></tag>
   <elementGuidId>fb5adf87-dbdb-415e-88b2-f0a0e32ad338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pop-up-banner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pop-up-banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f8ef6b60-31c5-4fac-9054-cab45e43fe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pop-up-banner</value>
      <webElementGuid>7daac44c-a8e1-4af3-b949-f1fb8a28e184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>popup landing</value>
      <webElementGuid>94425026-7257-4535-b1ed-f3e5c80705ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>06f73fe4-34ad-469d-ae39-28c1a9bf5c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>576</value>
      <webElementGuid>e1a600d1-87cf-42c6-8265-2a6ca49c933e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>576</value>
      <webElementGuid>5e98bff7-af79-4e53-9490-e12bba860b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>30757c1d-d24d-487f-af32-4b2873af8db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>82e46009-dc67-4434-8c36-f7c4a6b657d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-auto max-h-[90vh] w-full object-contain</value>
      <webElementGuid>76b51a4b-a7ff-40a4-83a0-a52bdf751f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fstatic-src.vocagame.com%2Fvocagame%2FKV2%20VOCAGAME%20POP%20UP%20BG%20hires.webp&amp;w=640&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fstatic-src.vocagame.com%2Fvocagame%2FKV2%20VOCAGAME%20POP%20UP%20BG%20hires.webp&amp;w=1200&amp;q=75 2x</value>
      <webElementGuid>dcc7ac54-3d6e-4c5e-9e7b-cfa22f58a1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fstatic-src.vocagame.com%2Fvocagame%2FKV2%20VOCAGAME%20POP%20UP%20BG%20hires.webp&amp;w=1200&amp;q=75</value>
      <webElementGuid>38639e08-36b1-44a5-8827-4c62f0a9dc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pop-up-banner&quot;)</value>
      <webElementGuid>299adf16-391d-4ebd-bced-6ef8a3303250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pop-up-banner']</value>
      <webElementGuid>33cdefa8-0897-4c20-ac2d-4da7df5971b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r0:']/div/a/img</value>
      <webElementGuid>c42a4b75-585c-4ee0-91af-d4fe49c40645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='popup landing']</value>
      <webElementGuid>3d873c4a-3879-4b20-af91-38189ed90ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>28b71b7e-f60b-4c4d-b120-f2d0d9aab53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pop-up-banner' and @alt = 'popup landing' and @src = '/_next/image?url=https%3A%2F%2Fstatic-src.vocagame.com%2Fvocagame%2FKV2%20VOCAGAME%20POP%20UP%20BG%20hires.webp&amp;w=1200&amp;q=75']</value>
      <webElementGuid>4db1a6ef-31b8-4ecd-9a9f-f90900c1865e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
