<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show_password</name>
   <tag></tag>
   <elementGuidId>91f09584-4044-4e80-9c00-281bef374c7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @name='password']
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7f3d3fb-f103-41c2-a81f-96a728a350d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>96318965-7e47-4350-ab23-02e6ef108996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex w-full rounded-md border-border-secondary px-3 py-2 text-sm transition-colors ease-in-out file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-secondary-foreground focus-visible:outline-none focus:border-2 focus:border-primary disabled:cursor-not-allowed disabled:opacity-50 !h-12 border !bg-transparent hide-password-toggle pr-10 h-12 min-w-full bg-transparent</value>
      <webElementGuid>2ca2d5c1-ca5f-47eb-8983-dbb5fcc89953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r0:-form-item</value>
      <webElementGuid>c87ea88c-316f-4e21-bce7-a5801af75357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r0:-form-item-description :r0:-form-item-message</value>
      <webElementGuid>ae2ad77d-6de5-46b8-87cc-bcbd0b36c403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2f3a89b3-5076-41b3-9552-c528b477f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bf238386-4bef-47bb-a2a4-3f45c618b812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3b459e03-ff58-4a5b-9b91-ed0e6b480777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r0:-form-item&quot;)</value>
      <webElementGuid>103b43e0-6465-4781-8091-042c5e696b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':r0:-form-item']</value>
      <webElementGuid>71ffec07-0eed-4c44-bc9b-24edd3243be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5ad0a6e9-4166-4563-a334-162028b51236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':r0:-form-item' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>32ecf509-046f-48b9-ad65-bd7f1fd1ce9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
